// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `czc/pkg/errors`
func init() {
	register(ErrConnectDB, 500, "Internal server error")
	register(ErrGoodsNotFound, 500, "Internal server error")
	register(ErrUserNotFound, 404, "User not found")
	register(ErrUserAlreadyExists, 400, "User already exists")
	register(ErrUserPasswordIncorrect, 400, "User password is incorrect")
	register(ErrSmsSend, 400, "Send sms error")
	register(ErrJWTDeploy, 500, "JWT deploy error")
	register(ErrJWTReadFiled, 500, "JWT read field error")
	register(ErrInvalidPrivKey, 500, "Internal server error")
	register(ErrFailedTokenCreation, 500, "Internal server error")
	register(ErrCodeNotExist, 400, "Sms code incorrect or expired")
	register(ErrCodeExpired, 400, "Sms code expired")
}
