// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `czc/pkg/errors`
func init() {
	register(ErrConnectDB, 500, "Internal server error")
	register(ErrEsDatabase, 404, "EsDatabase error")
	register(ErrEsUnmarshal, 500, "Es unmarshal error")
	register(ErrConnectGRPC, 500, "Connect to grpc error")
	register(ErrRedisDatabase, 500, "Redis data base error")
	register(ErrGoodsNotFound, 404, "Goods not found")
	register(ErrCategoryNotFound, 404, "Category not found")
	register(ErrBrandsNotFound, 404, "Brand not found")
	register(ErrBannerNotFound, 404, "Banner not found")
	register(ErrCategoryBrandsNotFound, 404, "CategoryBrands not found")
	register(ErrInventoryNotFound, 404, "Goods not found")
	register(ErrInvSellDetailNotFound, 400, "Inventory sell detail not found")
	register(ErrInvNotEnough, 404, "Inventory not enough")
	register(ErrstockNotFound, 404, "Order not found")
	register(ErrOrderNotFound, 404, "Order not found")
	register(ErrShopCartNotFound, 404, "ShopCart not found")
	register(ErrOrderDtm, 404, "Dtm unknonwn error")
	register(ErrNotGoodsSelect, 404, "No Goods selected")
	register(ErrUserNotFound, 404, "User not found")
	register(ErrUserAlreadyExists, 400, "User already exists")
	register(ErrUserPasswordIncorrect, 400, "User password is incorrect")
	register(ErrSmsSend, 400, "Send sms error")
	register(ErrJWTDeploy, 500, "JWT deploy error")
	register(ErrJWTReadFiled, 500, "JWT read field error")
	register(ErrInvalidPrivKey, 500, "Internal server error")
	register(ErrFailedTokenCreation, 500, "Internal server error")
	register(ErrCodeNotExist, 400, "Sms code incorrect or expired")
	register(ErrCodeExpired, 400, "Sms code expired")
}
