// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ERR_CODE_OK-0]
	_ = x[ERR_CODE_INVALID_PARAM-1]
	_ = x[ERR_CODE_TIMEOUT-2]
}

const _ErrCode_name = "okinvalid parametertimeout"

var _ErrCode_index = [...]uint8{0, 2, 19, 26}

func (i ErrCode) String() string {
	if i < 0 || i >= ErrCode(len(_ErrCode_index)-1) {
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrCode_name[_ErrCode_index[i]:_ErrCode_index[i+1]]
}
